-- MySQL Script generated by MySQL Workbench
-- Sat Jun  5 12:16:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`kurz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`kurz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`kurz` (
  `idKurz` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NULL,
  `pocet_mist` INT NULL,
  `popis` TEXT NULL,
  `cena` INT NULL,
  `misto` TEXT(45) NULL,
  `uzavreni` TIMESTAMP NULL,
  PRIMARY KEY (`idKurz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uzivatel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`uzivatel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel` (
  `idUzivatel` INT NOT NULL AUTO_INCREMENT,
  `heslo` CHAR(60) NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `funkce` TEXT(45) NULL,
  `kurz_idKurz` INT NULL,
  `fronta_idKurz` INT NULL,
  PRIMARY KEY (`idUzivatel`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
